server:
  port: 8080

spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mariadb://mariadb:3306/auth_db}
    driver-class-name: "org.mariadb.jdbc.Driver"
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:sapassword}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: ${DBKK_CONNECTION:kafka}:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  data:
    redis:
      host: ${DBKK_CONNECTION:redis}
      port: 6379
      database: 0
  cloud:
    openfeign:
      client:
        config:
          user-service:
            url: ${FEIGN_USER:http://user-service:8082}
            connect-timeout: 60000
            read-timeout: 120000
          default:
            connect-timeout: 60000
            read-timeout: 120000
jwt:
  signerKey: ${JWT_SIGNERKEY:1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij}
  valid-duration: 3600 #in seconds
  refreshable-duration: 360000 #in seconds

invalid-token:
  cleanup:
    enabled: true
    cron: "0 0 2 * * MON"   # 2:00 sáng Thứ Hai hằng tuần
    batch-size: 500
